BWDB-15635: Iris V2 API migration guide framework.
Bandwidth/api-docs pull request #1115
Opened 2023-08-07 14:39 UTC by severhardt-bw

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

2023-08-07 15:01 UTC, ajrice6713 requested changes

2023-08-07 15:18 UTC, ajrice6713 submitted a review, later dismissed

2023-08-07 15:41 UTC, mrmeyers99 commented on site/docs/numbers/v2Migration.mdx
> +- Update your Jasper Report requests to use the v2 routes
I think this is redundant.

2023-08-07 15:41 UTC, mrmeyers99 commented on site/docs/numbers/v2Migration.mdx
> +ex. +1(980)5556666
```suggestion
ex. +19805556666
```

2023-08-07 15:42 UTC, mrmeyers99 commented on site/sidebar.js
> +        // "numbers/numbersApiV2",
what is this for?

2023-08-07 16:56 UTC, mrmeyers99 commented on site/sidebar.js
> +        // "numbers/numbersApiV2",
we spoke in person and this will be uncommented when we're ready for customers to see it

2023-08-07 17:00 UTC, mrmeyers99 approved these changes

2023-08-10 13:09 UTC, ajrice6713 approved these changes

2023-08-10 13:28 UTC, merged