BWDB-15919 Add order changed timestamp to Iris order webhook notifications
Bandwidth/api-docs pull request #1147
Opened 2023-09-12 15:35 UTC by areddy-bw

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

2023-09-12 16:27 UTC, jdunster-bw commented on site/docs/numbers/orderWebhook.md
> +| `ActualFocDate` | `Date` | Actual FOC date, provided only if the order is in "foc" status. |
```suggestion
| `ActualFocDate` | `Date` | Actual FOC date, provided only if the order is a port-in transitioning to "FOC" status. |
```

2023-09-12 18:06 UTC, jdunster-bw submitted a review, later dismissed

2023-09-14 13:44 UTC, evanhalley requested changes
There was an extra closing Notification tag

2023-09-14 13:44 UTC, evanhalley commented on site/docs/numbers/orderWebhook.md
> +    <ActualFocDate>2023-09-12T00:00:00Z</ActualFocDate></Notification>
```suggestion
    <ActualFocDate>2023-09-12T00:00:00Z</ActualFocDate>
```

2023-09-14 13:48 UTC, evanhalley approved these changes

2023-09-14 17:31 UTC, jdunster-bw approved these changes

2023-09-15 21:47 UTC, raghunath-thota approved these changes

2023-09-18 08:31 UTC, merged