DX-2141
Bandwidth/api-docs pull request #222
Opened 2021-08-17 12:45 UTC by ajrice6713

Add Object property descriptions

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-08-20 20:34 UTC, hamermike requested changes

2021-08-20 20:34 UTC, hamermike commented on site/specs-source/dash.json
> +            "description": "Time  that the most recent address was activated (provisioned) for the endpoint (in UTC)"
```suggestion
            "description": "Time that the most recent address was activated (provisioned) for the endpoint (in UTC)"
```

2021-08-20 20:34 UTC, hamermike commented on site/specs-source/dash.json
> +                    "description": "Effectively the phone number of the subscriber.  The URI can include the \"tel:\" prefix, but it's not required."
```suggestion
                    "description": "Effectively the phone number of the subscriber. The URI can include the \"tel:\" prefix, but it's not required."
```

2021-08-20 20:34 UTC, hamermike commented on site/specs-source/dash.json
> +                "description": "Effectively the phone number of the subscriber.  The URI can include the \"tel:\" prefix, but it's not required."
```suggestion
                "description": "Effectively the phone number of the subscriber. The URI can include the \"tel:\" prefix, but it's not required."
```

2021-08-20 20:34 UTC, hamermike commented on site/specs-source/dash.json
> +            "description": "Time  that the most recent address was activated (provisioned) for the endpoint (in UTC)"
```suggestion
            "description": "Time that the most recent address was activated (provisioned) for the endpoint (in UTC)"
```

2021-08-20 20:38 UTC, hamermike approved these changes

2021-08-23 13:46 UTC, jmulford-bw approved these changes
Approving assuming there will be future changes to fix the examples

2021-08-23 13:48 UTC, merged