DX-2180 Update Node BXML examples
Bandwidth/api-docs pull request #243
Opened 2021-09-07 19:59 UTC by ajrice6713

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-09-07 20:31 UTC, ckoegel requested changes

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/speakSentence.mdx
> +    voice: "Julie"
```suggestion
    voice: "julie"
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/speakSentence.mdx
> +    voice: "Julie"
```suggestion
    voice: "julie"
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/bridge.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/bridge.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/forward.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/hangup.mdx
> +const hangup = new Hangup()
```suggestion
const hangup = new Hangup();
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/pause.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/pauseRecording.mdx
> +const pauseRecording = new PauseRecording()
```suggestion
const pauseRecording = new PauseRecording();
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/pauseRecording.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/sendDtmf.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/forward.mdx
>  ```
```suggestion
```python
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/startRecording.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/tag.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/tag.mdx
> +})
```suggestion
});
```

2021-09-07 20:31 UTC, ckoegel commented on site/docs/voice/bxml/tag.mdx
> +})
```suggestion
});
```

2021-09-07 21:03 UTC, hamermike requested changes

2021-09-08 13:13 UTC, hamermike requested changes

2021-09-08 13:13 UTC, hamermike commented on site/docs/voice/bxml/gather.mdx
> +    sentence: "SecondSentence"
```suggestion
    sentence: "Second Sentence."
```

2021-09-08 14:47 UTC, hamermike approved these changes

2021-09-08 15:20 UTC, ckoegel approved these changes

2021-09-08 15:29 UTC, merged