DX-2199 Add AMD to Voice API spec
Bandwidth/api-docs pull request #249
Opened 2021-09-08 19:51 UTC by ajrice6713

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-09-08 20:46 UTC, ckoegel approved these changes

2021-09-09 14:18 UTC, ajrice6713 commented
The change from `pai` to `stirShaken` is not breaking - this was changed in production back in May and the change now is a result of being out of sync with the voice teams copy of the spec

2021-09-09 15:30 UTC, hamermike requested changes

2021-09-09 15:30 UTC, hamermike commented on site/src/pages/changelog.md
> +| September 8th, 2021 | Added `MachineDetection` object to the Voice OpenAPI spec and bumped to version 3.1.0 |
```suggestion
| September 8th, 2021 | Added `MachineDetection` object to the Voice OpenAPI spec and bumped to version 3.2.0 | 
```

2021-09-09 15:42 UTC, hamermike approved these changes

2021-09-09 15:45 UTC, merged