DX-2195 Updated MFA OpenAPI Spec
Bandwidth/api-docs pull request #251
Opened 2021-09-08 20:15 UTC by ckoegel

2021-09-08 20:54 UTC, hamermike requested changes

2021-09-08 20:54 UTC, hamermike commented on site/specs-source/multiFactorAuth.json
> +        "summary": "Two-Factor Verify Code",
```suggestion
        "summary": "Verify Authentication Code",
```
I know we had the prior in the old docs but... Thoughts?

2021-09-08 20:54 UTC, hamermike commented on site/specs-source/multiFactorAuth.json
> +        "description": "Two-Factor authentication with Bandwidth Messaging services. Allows a user to send an MFA code via a text message (SMS)",
```suggestion
        "description": "Multi-Factor authentication with Bandwidth Messaging services. Allows a user to send an MFA code via a text message (SMS).",
```

2021-09-08 20:54 UTC, hamermike commented on site/specs-source/multiFactorAuth.json
> +        "description": "Two-Factor authentication with Bandwidth Voice services. Allows for a user to send an MFA code via a phone call.",
```suggestion
        "description": "Multi-Factor authentication with Bandwidth Voice services. Allows for a user to send an MFA code via a phone call.",
```

2021-09-08 21:04 UTC, hamermike approved these changes

2021-09-09 12:40 UTC, ajrice6713 approved these changes

2021-09-09 15:46 UTC, merged