DX-2197 Updated TN Lookup OpenAPI Spec
Bandwidth/api-docs pull request #253
Opened 2021-09-08 20:57 UTC by ckoegel

2021-09-08 21:07 UTC, hamermike requested changes

2021-09-08 21:07 UTC, hamermike commented on site/specs-source/phoneNumberLookup.json
> +        "description": "Query an existing TN Lookup Order",
```suggestion
        "description": "Query an existing TN Lookup Order.",
```

2021-09-08 21:10 UTC, hamermike approved these changes

2021-09-09 12:39 UTC, ajrice6713 approved these changes

2021-09-09 15:47 UTC, merged