DX-2192 Update Voice API Spec
Bandwidth/api-docs pull request #255
Opened 2021-09-09 16:33 UTC by ajrice6713

Update Tags, Summaries, and Descriptions of each endpoint to better display the reference on the docsite

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-09-09 16:50 UTC, hamermike requested changes

2021-09-09 16:50 UTC, hamermike commented on site/specs-source/voice.json
>          "description": "Returns a (potentially empty) list of metadata for the recordings that took place during the specified call",
```suggestion
        "description": "Returns a (potentially empty) list of metadata for the recordings that took place during the specified call.",
```

2021-09-09 17:20 UTC, abaldwin-Bandwidth requested changes
Recordings API call name verbiage was awkward

2021-09-09 17:20 UTC, abaldwin-Bandwidth commented on site/specs-source/voice.json
> +        "summary": "Get Recordings",
```suggestion
        "summary": "Get Call Recordings",
```

2021-09-09 17:20 UTC, abaldwin-Bandwidth commented on site/specs-source/voice.json
> +        "summary": "Get Recording Information",
```suggestion
        "summary": "Get Call Recording",
```

2021-09-09 19:58 UTC, hamermike approved these changes

2021-09-10 13:27 UTC, abaldwin-Bandwidth approved these changes

2021-09-10 13:28 UTC, merged