task/add survey link
Bandwidth/api-docs pull request #275
Opened 2021-09-27 19:34 UTC by ajrice6713

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-09-27 20:03 UTC, hamermike requested changes

2021-09-27 20:03 UTC, hamermike commented on site/docusaurus.config.js
> +            content: 'Welcome to the new home of Bandwidth\'s Developer Documentation. Please take a minute to <a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSdX1vzY2_yqcNIWMwPkcrv
```suggestion
            content: 'Welcome to the new home of Bandwidth\'s Developer Documentation. Please take a minute to <a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSdX1vzY2_yqcNIWMwPkcrvd6lJG-899qNviQf1iR-JZvGLw6g/viewform?usp=sf_link">provide any feedback you may have</a> on our new docsite!',
```

2021-09-27 20:14 UTC, hamermike approved these changes

2021-09-28 13:18 UTC, ckoegel approved these changes

2021-09-28 13:22 UTC, merged