DX-2304 Add cURL samples for TN Lookup
Bandwidth/api-docs pull request #303
Opened 2021-11-10 17:31 UTC by ajrice6713

Added create and query samples

updated `add-code-snippets-oas.js` to convert .sh files to curl

started curl env replacement file

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-11-10 17:50 UTC, ckoegel submitted a review, later dismissed

2021-11-10 18:44 UTC, hamermike requested changes

2021-11-10 18:44 UTC, hamermike commented on site/code-snippets/PhoneNumberLookup/LookupRequestStatus/1-curl.sh
> +    --header 'Authorization: Basic $cURL_AUTH'
```suggestion
curl https://numbers.bandwidth.com/api/v1/accounts/$BW_ACCOUNT_ID/tnlookup/004223a0-8b17-41b1-bf81-20732adf5590 \
    -H 'Authorization: Basic $cURL_AUTH'
```

2021-11-10 18:44 UTC, hamermike commented on site/code-snippets/PhoneNumberLookup/LookupRequest/1-curl.sh
> +    }'
```suggestion
curl https://numbers.bandwidth.com/api/v1/accounts/$BW_ACCOUNT_ID/tnlookup \
    -X POST \
    -H 'Authorization: Basic $cURL_AUTH' \
    -H 'Content-Type: application/json' \
    -d '{
        "tns":
        [
            "19196104420"
        ]
    }'
```

2021-11-11 20:52 UTC, ajrice6713 commented
This was merged in a later PR

2021-11-11 20:52 UTC, closed without merging