DX-2299 Fixed Vertical Alignment of HTTP Methods in API Reference
Bandwidth/api-docs pull request #304
Opened 2021-11-10 18:32 UTC by ckoegel

2021-11-10 18:48 UTC, ajrice6713 submitted a review, later dismissed

2021-11-10 18:51 UTC, hamermike requested changes

2021-11-10 18:51 UTC, hamermike commented on site/src/css/custom.css
> +  margin-top: 4px;
```suggestion
  margin-block: auto;
```
I didn't test in all browsers but if that works I like it better than the magic number. Also, the `4px` didn't align exactly on my machine, it was better though. 🥈

2021-11-11 16:48 UTC, hamermike approved these changes

2021-11-11 20:00 UTC, merged