DX-2272 Added cURL Messaging Snippets and Renamed Files
Bandwidth/api-docs pull request #308
Opened 2021-11-11 17:57 UTC by ckoegel

the only modified files are the `0-curl.sh` files. All others are just renamed

2021-11-11 19:15 UTC, ajrice6713 approved these changes

2021-11-11 21:07 UTC, hamermike requested changes

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/GetMedia/Curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/GetMedia/curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/GetMessages/Curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/GetMessages/curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/ListMedia/Curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/Messaging/ListMedia/curl.sh
> +    -X GET \
```suggestion
```

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/MultiFactorAuth/messagingTwoFactor/curl.sh
> +    }'
Swap to the shorthand.

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/PhoneNumberLookup/LookupRequest/curl.sh
> +    }'
Swap to the shorthand

2021-11-11 21:07 UTC, hamermike commented on site/code-snippets/PhoneNumberLookup/LookupRequestStatus/curl.sh
> +    --header 'Authorization: Basic $cURL_AUTH'
Swap to the shorthand.

2021-11-11 22:18 UTC, ajrice6713 requested changes

2021-11-11 22:18 UTC, ajrice6713 commented on site/scripts/env-replace/curl.json
> +    "$BW_PASSWORD": "pi-password",
```suggestion
    "$BW_PASSWORD": "api-password",
```

2021-11-12 14:11 UTC, hamermike approved these changes

2021-11-12 14:12 UTC, ajrice6713 approved these changes

2021-11-12 14:14 UTC, merged