VAPI-1 Update AMD documentation
Bandwidth/api-docs pull request #309
Opened 2021-11-11 20:12 UTC by tmoney-bw

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2021-11-11 20:38 UTC, nashley commented
Related to https://github.com/Bandwidth/bandwidth.github.io/pull/719

2021-11-11 22:16 UTC, nashley requested changes

2021-11-11 22:16 UTC, nashley commented on site/docs/voice/webhooks/answer.mdx
> +    "machineDetectionResult": "answering-machine"
```suggestion
    "machineDetectionResult": {
        "value":  "answering-machine",
        "duration": "PT5.023724322S"
    }
```

2021-11-11 22:19 UTC, nashley commented
Links work. It's a shame we can't link directly to `machineDetection` in `POST /calls` anymore with the new doc site :/

2021-11-12 15:56 UTC, nashley approved these changes

2021-11-12 15:58 UTC, nashley requested changes
lol sorry for changing my mind again
`duration` should be a reasonable value given `startTime` and `eventTime`. We should probably just use a real ~callback~ webhook example.

2021-11-12 20:13 UTC, nashley approved these changes

2021-11-12 20:15 UTC, nashley requested changes
Bad json

2021-11-12 21:08 UTC, nashley approved these changes

2021-11-12 21:29 UTC, vsmith-bw approved these changes

2021-11-12 21:30 UTC, merged