DX-2321 Fix Links for Cutover
Bandwidth/api-docs pull request #333
Opened 2022-01-06 14:28 UTC by ajrice6713

## For the Committer

All PRs on this repo that change any API sources of truth (markdown files, OpenAPI specs) require a changelog added to the `site/src/pages/changelog.md` file. If this PR does not require changelog updates, you need to add the `no-changelog` tag to this PR before opening it.

Please confirm that you have either updated `site/src/pages/changelog.md` or added the `no-changelog` tag.

2022-01-06 14:28 UTC, ajrice6713 commented
Do not merge until 1/10

2022-01-06 14:42 UTC, hamermike requested changes

2022-01-06 14:42 UTC, hamermike commented on site/docs/webrtc/quickstart.md
> +This gives you lots of flexibility and control over what each participant receives and sends in a session. You can find more about sessions in our [API documentation](https://https://dev.bandwidth.co
```suggestion
This gives you lots of flexibility and control over what each participant receives and sends in a session. You can find more about sessions in our [API documentation](https://dev.bandwidth.com/apis/webrtc/#tag/Sessions).
```

2022-01-06 15:36 UTC, hamermike approved these changes

2022-01-07 15:41 UTC, ckoegel approved these changes

2022-01-10 14:22 UTC, merged