DX-2388
Bandwidth/api-docs pull request #340
Opened 2022-01-11 19:11 UTC by ckoegel

2022-01-11 19:13 UTC, ajrice6713 submitted a review, later dismissed

2022-01-11 21:08 UTC, hamermike approved these changes

2022-01-12 15:21 UTC, ajrice6713 approved these changes

2022-01-12 15:21 UTC, hamermike requested changes

2022-01-12 15:21 UTC, hamermike commented on site/docusaurus.config.js
> +                        from: '/messaging/errors/codes',    // /messaging/errors/codes.html#error-code-schema
```suggestion
                        from: '/messaging/errors/codes', // /messaging/errors/codes.html#error-code-schema
```

2022-01-12 15:28 UTC, hamermike approved these changes

2022-01-12 18:10 UTC, ajrice6713 approved these changes

2022-01-12 18:53 UTC, merged