DX-2449 Prep for New Pipeline
Bandwidth/api-docs pull request #381
Opened 2022-02-24 18:11 UTC by ckoegel

2022-02-24 20:48 UTC, ajrice6713 submitted a review, later dismissed

2022-02-24 22:06 UTC, hamermike requested changes

2022-02-24 22:06 UTC, hamermike commented on site/scripts/add-code-snippets-oas.js
> +const SPEC_SOURCE_DIRECTORY = 'specs/';
This could be cleaned up a bit by using a single variable since the source and destination are now the same.

2022-02-25 14:35 UTC, ajrice6713 approved these changes

2022-02-25 15:16 UTC, hamermike approved these changes

2022-02-25 15:18 UTC, merged