Task/numbers
Bandwidth/api-docs pull request #476
Opened 2022-04-11 10:46 UTC by aharin90

2022-04-11 13:31 UTC, mrmeyers99 commented on site/specs/numbers.json
> +            "description": "Successful response <br> The \"Links\" element includes two links.  The link called \"first\" is the link to the first set of results for the query that was submitted.  If
You could also you `\`first\`` instead of `\"first\"` which would format it nicely

2022-04-11 14:37 UTC, ajrice6713 requested changes

2022-04-14 09:54 UTC, aharin90 commented on site/specs/numbers.json
> +            "description": "Successful response <br> The \"Links\" element includes two links.  The link called \"first\" is the link to the first set of results for the query that was submitted.  If
tried to change " to ` - but it looks bad, so I changed it back

2022-04-14 17:06 UTC, ajrice6713 approved these changes

2022-04-15 15:44 UTC, mrmeyers99 commented
In general I would like to see `\`` instead of `"` for referencing field names, but this is something we could change later I guess.

2022-04-15 15:45 UTC, mrmeyers99 commented on site/specs/numbers.json
> +            "description": "<p>Bad request </p><br> <p><b>Condition:</b> Unrecognized query parameter <br> <b>Error Description:</b>Query parameter xxx is not recognized. </p> <br> <p><b>Condition:</
does this display properly with the nested `<p>` tags?

2022-04-26 13:35 UTC, mrmeyers99 commented
@aharin90 can you respond to comments and resolve the conflict with the target branch?

2022-04-26 15:40 UTC, mrmeyers99 approved these changes

2022-04-26 15:40 UTC, merged