How to search and order a phone number guide
Bandwidth/api-docs pull request #633
Opened 2022-07-20 12:27 UTC by safronenko23

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

2022-07-22 20:31 UTC, ajrice6713 requested changes

2022-07-22 20:31 UTC, ajrice6713 commented on site/docs/numbers/searchingNumbers.mdx
> +To make a search for the available number, you must make a GET request to our [API available numbers](../../../../apis/numbers#tag/accounts/operation/GetAvailableTns) endpoint.
```suggestion
To make a search for the available number, you must make a GET request to our [available numbers API](../../../../apis/numbers#tag/accounts/operation/GetAvailableTns) endpoint.
```

2022-07-22 20:31 UTC, ajrice6713 commented on site/docs/numbers/searchingNumbers.mdx
> +This can be done through our [SDKs](/sdks), using tools like [Postman](https://github.com/Bandwidth/postman) or in the command line.
We dont link to the IRIS SDKs anywhere so id remove any reference to SDKs when talking about numbers apis

2022-07-22 20:31 UTC, ajrice6713 commented on site/docs/numbers/searchingNumbers.mdx
>  <Tabs
Is there a reason for replacing the different number search types with sdk examples? 

We dont really support the sdks and below is missing python and ruby

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +In this example, we will show how to make an order for numbers that were found using the search.
```suggestion
In this example, we will show how to create an order for numbers that were found using the search.
```

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +This can be done through our [SDKs](/sdks), using tools like [Postman](https://github.com/Bandwidth/postman) or in the command line.
```suggestion
This can be done through tools like [Postman](https://github.com/Bandwidth/postman) or in the command line.
```

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +Phone number ordering in the Bandwidth Dashboard is asynchronous when creating an "order". The orders are then processed and the order status is updated asynchronously.  Bandwidth recommends configur
can you add a link to the subscriptions reference on the word "subscriptions"?

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +## Poll for Order Status
Can we remove the poll section? I don't know that it makes sense to include since we don't recommend this method.

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +To create a subscription for Order Status you must to send POST request to our [API create subscription](../../../../apis/numbers#tag/accounts/operation/CreateSubscriptions) endpoint.
```suggestion
To create a subscription for Order Status you must send a POST request to our [API create subscription](../../../../apis/numbers#tag/accounts/operation/CreateSubscriptions) endpoint.
```

2022-07-28 13:15 UTC, rjamesq commented on site/docs/numbers/searchingNumbers.mdx
> +Now that you have learn how to search and order numbers, check out some of the available actions in the guides:
```suggestion
Now that you have learned how to search and order numbers, check out some of the other available actions in our guides:
```

2022-07-28 14:43 UTC, safronenko23 commented on site/docs/numbers/searchingNumbers.mdx
> +Ordering Phone Numbers for use with the network allows you to provision specific phone numbers from available inventory that have been discovered in a search.
Seems like AJ already made a comment for this. Please check my updates for this.

2022-07-30 18:28 UTC, ajrice6713 commented
@rjamesq is this approved?

2022-08-03 11:10 UTC, safronenko23 commented
@rjamesq any comments on that?

2022-08-03 13:47 UTC, rjamesq commented on site/docs/numbers/searchingAndOrderingNumbers.mdx
> +Bandwidth allows you to provision specific phone numbers from available inventory for use with the network.
```suggestion
```

2022-08-03 13:47 UTC, rjamesq commented on site/docs/numbers/searchingAndOrderingNumbers.mdx
> +We offer an API that allows you to search our inventory and purchase numbers for use with our network.
```suggestion
Bandwidth offers an API that allows you to search our inventory and purchase numbers for use with our network.
```

2022-08-03 13:47 UTC, rjamesq commented on site/docs/numbers/searchingAndOrderingNumbers.mdx
> +In this guide we will show you how to search for available phone numbers and order them through API.
```suggestion
In this guide we will show you how to search for available phone numbers and order them through the API.
```

2022-08-05 13:34 UTC, safronenko23 commented
![Uploading search_examle.png…]()

2022-08-12 13:19 UTC, safronenko23 commented
@ajrice6713 @rjamesq Any comments on this?

2022-08-12 17:16 UTC, ajrice6713 approved these changes

2022-08-12 18:17 UTC, rjamesq approved these changes

2022-08-12 18:24 UTC, merged