api-reference - new tags v2.
Bandwidth/api-docs pull request #692
Opened 2022-08-30 09:16 UTC by maksymmateiuk

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

2022-08-30 13:08 UTC, brianluisgomez approved these changes, later dismissed

2022-09-01 13:04 UTC, ajrice6713 requested changes

2022-09-01 13:04 UTC, ajrice6713 commented on site/specs-temp/numbers.json
> +          "Bulk port-in"
```suggestion
          "Bulk Port-In"
```
Tags should be `Title Case`

2022-09-01 14:17 UTC, ajrice6713 commented on site/specs-temp/numbers.json
> +          "Bulk port-in"
@maksymmateiuk can you repeat for all of the Bulk Port-In tags? 

looks like `I` was missed in last commit as well.

2022-09-01 17:37 UTC, ajrice6713 approved these changes

2022-09-01 18:18 UTC, brianluisgomez approved these changes

2022-09-01 18:18 UTC, merged