TN Lookup guide update
Bandwidth/api-docs pull request #720
Opened 2022-09-13 09:07 UTC by safronenko23

**⚠️Please do not make any changes to spec files in this repository!⚠️**

**All spec changes should be done in the [api-specs](https://github.com/Bandwidth/api-specs) repository.**

**Please follow the [Guide](https://bandwidth-jira.atlassian.net/wiki/spaces/DX/pages/4098359409/How+to+Update+API+Specifications+and+Contribute+to+Developer+Documentation) for contributing to our developer documentation.**

2022-09-14 17:23 UTC, gocab-bw requested changes

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
>  ## Submit Number Lookup Order
Can we change the use of "order" to "request" in all instances in this document?

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +To submit number Lookup request, make a <Highlight color="#079CEE">POST</Highlight> request to our [Create Lookup Order API](../../../../apis/number-lookup#tag/Phone-Number-Lookup/operation/createLoo
```suggestion
To start the process of looking up information for a phone number, make a <Highlight color="#079CEE">POST</Highlight> request to the [Create Lookup Request API](../../../../apis/number-lookup#tag/Phone-Number-Lookup/operation/createLookup) endpoint.
```

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +Since the TN Lookup request is asynchronous it means that you need to make a <Highlight color="#00bf8c">GET</Highlight> request
```suggestion
Since the TN Lookup request processing is asynchronous,  make a <Highlight color="#00bf8c">GET</Highlight> request
```

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +to our [Get Lookup Order Status API](../../../../apis/number-lookup#tag/Phone-Number-Lookup/operation/getLookupStatus) endpoint to get the request status.
```suggestion
to our [Get Lookup Order Status API](../../../../apis/number-lookup#tag/Phone-Number-Lookup/operation/getLookupStatus) endpoint to determine the status.
```

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +Now that you have learned how to lookup for numbers, check out some of the other available actions in our guides:
```suggestion
Now that you have learned how to lookup information for phone numbers, check out some of the other available actions in our guides:
```

2022-09-14 17:23 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +- [How to port numbers](/docs/numbers/guides/porting/portingNumbers)
I would suggest leaving out the link to the port numbers guide.  Customers may think that this is used in that workflow when it should not be.

2022-09-15 13:20 UTC, gocab-bw requested changes
Hi Mikhail, just a few more places to change "order" to "request".  Let me know if any of these can't be done for some reason.

2022-09-15 13:20 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
>  <Highlight color="#00bf8c">GET</Highlight> <code>https://numbers.bandwidth.com/api/v1/accounts/{accountId}/tnlookup/{orderId}</code>
```suggestion
<Highlight color="#00bf8c">GET</Highlight> <code>https://numbers.bandwidth.com/api/v1/accounts/{accountId}/tnlookup/{requestId}</code>
```

2022-09-15 13:20 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
> +curl 'https://numbers.bandwidth.com/api/v1/accounts/{accountId}/tnlookup/{orderId}'
```suggestion
curl 'https://numbers.bandwidth.com/api/v1/accounts/{accountId}/tnlookup/{requestId}'
```

2022-09-15 13:20 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
>    groupId="http_number_lookup_order_status"
```suggestion
  groupId="http_number_lookup_request_status"
```

2022-09-15 13:20 UTC, gocab-bw commented on site/docs/numbers/lookupNumbers.mdx
>    groupId="http_number_lookup_order"
```suggestion
  groupId="http_number_lookup_request"
```

2022-09-15 13:42 UTC, gocab-bw approved these changes, later dismissed

2022-09-15 17:14 UTC, rjamesq commented on site/docs/numbers/lookupNumbers.mdx
> +The request status can be in one of these examples:
```suggestion
At a given time, the request status for requests made can be 'IN PROGRESS', 'COMPLETE', or 'FAILED'. For requests on multiple TNs, that status can also be 'PARTIAL_COMPLETE'. Please refer to the examples below to see possible responses:
```

2022-09-15 17:14 UTC, rjamesq commented on site/docs/numbers/lookupNumbers.mdx
>  <TabItem value="one_tn_complete">
labels should be "COMPLETE - One TN", "COMPLETE - Multiple TNs", "COMPLETE - No Information", "PARTIAL_COMPLETE - Multiple TNs" 

In other words, please add the status before the additional info :)

2022-09-16 13:13 UTC, gocab-bw requested changes

2022-09-16 13:22 UTC, gocab-bw approved these changes

2022-09-19 20:21 UTC, rjamesq approved these changes

2022-09-19 20:24 UTC, ajrice6713 approved these changes

2022-09-19 20:24 UTC, merged