DX-3022
Bandwidth/api-docs pull request #864
Opened 2022-12-07 21:36 UTC by ckoegel

2022-12-09 15:06 UTC, bpateldx commented on site/src/css/components/_Carousel.scss
> +        height: 19.8rem;
Thinking out loud here... can the style properties that are proportional (height, font-size) be declared as:
```
$base-font-size: 2.2em;
.base-container{
    font-size: $base-font-size;
    .something-smaller {
         font-size: $base-font-size - 0.2em; or $base-font-size - math.div($base-font-size , 0.11em)
    }
}
```
My syntax may not be accurate but hope it makes sense-:)

2022-12-09 15:34 UTC, bpateldx requested changes
Using Sass would be really beneficial to maintain different components with ease. This is awesome.

Did you end-up using any linter for sass files? If not, may be worth finding one. 

Please see if there is any opportunity to pull common properties out as commented.

2022-12-09 19:46 UTC, ajrice6713 requested changes

2022-12-09 19:46 UTC, ajrice6713 commented on site/src/css/components/_FeaturePanel.scss
> +        padding-top: 2px;
🤮

2022-12-09 19:46 UTC, ajrice6713 commented on site/src/css/components/_SdkPage.scss
> +                        border-radius: 0 0 0 20px;
```suggestion
                        border-radius: 0 0 0 🤮;
```

2022-12-09 19:46 UTC, ajrice6713 commented on site/src/css/components/_SdkPage.scss
> +                        border-radius: 0 0 20px 0;
```suggestion
                        border-radius: 0 0 🤮 0;
```

2022-12-09 19:46 UTC, ajrice6713 commented on site/src/css/components/modules/_CarouselSlide.scss
>              box-shadow: 0px 0px 20px $black-shadow;
[cmon man](https://giphy.com/gifs/joe-biden-town-hall-SWoRKslHVtqEasqYCJ)

2022-12-09 19:46 UTC, ajrice6713 commented on site/src/css/components/modules/_CarouselSlide.scss
> +            box-shadow: 0px 0px 10px $black-shadow;
![output-onlineimagetools](https://user-images.githubusercontent.com/53190766/206784158-37d8b1fb-3bbe-4063-a58a-290efe2f04ae.png)

2023-01-04 20:00 UTC, ajrice6713 approved these changes

2023-01-05 20:32 UTC, matthewkmartin approved these changes

2023-01-05 20:48 UTC, merged